const level1 = new Level(
    [
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new ChickenSmall(),
        new ChickenSmall(),
        new ChickenSmall(),
        new ChickenSmall(),
        new ChickenSmall(),
        new ChickenSmall()
    ],
    [
        new Endboss(),
    ],
    [
        new Cloud1(),
        new Cloud1(),
        new Cloud1(),
        new Cloud2(),
        new Cloud2(),
        new Cloud2()
    ],
    [
        new BottleL(),
        new BottleL(),
        new BottleL(),
        new BottleL(),
        new BottleL(),
        new BottleL(),
        new BottleL(),
        new BottleL(),
        new BottleR(),
        new BottleR(),
        new BottleR(),
        new BottleR(),
        new BottleR(),
        new BottleR(),
        new BottleR(),
        new BottleR()
        
    ],
    [
        new BottlesEnd('img/6.botella/2.Botella_enterrada1.png', 6500),
        new BottlesEnd('img/6.botella/2.Botella_enterrada1.png', 6600),
        new BottlesEnd('img/6.botella/2.Botella_enterrada2.png', 7030),
        new BottlesEnd('img/6.botella/2.Botella_enterrada2.png', 6555)
    ],
    [
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin()
    ],
    [
        new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', -2558),
        new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/1.png', -2558),
        new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/1.png', -2558),
        new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/1.png', -2558),
        new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', -1279),
        new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/2.png', -1279),
        new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/2.png', -1279),
        new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/2.png', -1279),
        new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 0),
        new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/1.png', 0),
        new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/1.png', 0),
        new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/1.png', 0),
        new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 1279),
        new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/2.png', 1279),
        new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/2.png', 1279),
        new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/2.png', 1279),
        new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 2558),
        new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/1.png', 2558),
        new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/1.png', 2558),
        new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/1.png', 2558),
        new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 3837),
        new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/2.png', 3837),
        new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/2.png', 3837),
        new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/2.png', 3837),
        new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 5116),
        new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/1.png', 5116),
        new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/1.png', 5116),
        new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/1.png', 5116),
        new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 6395),
        new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/2.png', 6395),
        new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/2.png', 6395),
        new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/2.png', 6395),
        new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 7674),
        new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/1.png', 7674),
        new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/1.png', 7674),
        new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/1.png', 7674)     
    ],
);